### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by coffeverton** [nucleos/lastfm#420]
Hi!
I'm trying to use this library, but the instructions on the readme doesn't seem to work.

The error message says that **Nucleos\LastFm\Service\PsrClientConnection** can't be found.

Also, where does **$httpClient** and **$requestFactory** came from?

Thanks!

**Comment by piewebnl** [comment]
Been puzzling a bit too,  you need to setup both own your own;
this worked for me;

Also the PsrClientConnection class is locatee in '\Connection' not ' Service'
So: use Nucleos\LastFm\Connection\PsrClientConnection; 

I used it in a laravel project, so these come from a config file
config('lastfm.last_fm_api_key'), config('lastfm.last_fm_shared_secret')
but you can use your own.

Create your api key and secret here;
https://www.last.fm/api/account/create

```

use GuzzleHttp\Client;
use Nucleos\LastFm\Client\ApiClient;
use Nyholm\Psr7\Factory\Psr17Factory;
use Nucleos\LastFm\Service\AuthService;
use Nucleos\LastFm\Service\ChartService;
use Nucleos\LastFm\Connection\PsrClientConnection;
use Nucleos\LastFm\Service\UserService;


$httpClient = new Client();
$factory = new Psr17Factory();
$connection = new PsrClientConnection($httpClient, $factory);

$apiClient = new ApiClient($connection, config('lastfm.last_fm_api_key'), config('lastfm.last_fm_shared_secret'));

// Create a session (with generated token)
$token = 'API token';
$authApi = new AuthService($apiClient);
$session = $authApi->createSession($token);

$chartService = new ChartService($apiClient);
$tags = $chartService->getTopTags(10);
//dd($tags);

$userName = '';
$userService = new UserService($apiClient);
$userInfo = $userService->getInfo($userName);
//dd($userInfo);

```

**Comment by core23** [comment]
I'm not actively using this lib anymore, but still maintaining it for dependency updates.

If you're using symfony, you might use the bundle https://github.com/nucleos/NucleosLastFmBundle

If there's something to improve in the docs, feel free to provide a PR.
